apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-bcknd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-bcknd
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-bcknd
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/back-end:4133711d6d0e61860a408d2e55d2b3cc8e024885
        name: guestbook-ui-bcknd
        ports:
        - containerPort: 80
