apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/front-end:b89a4879027c2c977dd077785fc5a1009dfecd7b
        name: guestbook-ui
        ports:
        - containerPort: 80

