apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-bcknd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-bcknd
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-bcknd
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/back-end:530c4757cd6b2b062ecb1b4e80d24341a5128672
        name: guestbook-ui-bcknd
        ports:
        - containerPort: 80
