apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode
        tst: tst-111127789
    spec:
      containers:
      - image: omniregistry/front-end:4f370fd4ba53afd5312ce0848bc6042d8e3b2de2
        name: guestbook-ui
        ports:
        - containerPort: 80

