apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/front-end:e4b5267011f61a0d3f3b9d6633d5e004cc2c2aa2
        name: guestbook-ui
        ports:
        - containerPort: 80

