apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-bcknd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-bcknd
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-bcknd
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/back-end:feea772d586f41ca44adf05dba80e62542fa7ce8
        name: guestbook-ui-bcknd
        ports:
        - containerPort: 80
