apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-bcknd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-bcknd
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-bcknd
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/back-end:a11cbf6220d2f7aaff04c83b731c02a746ea2efb
        name: guestbook-ui-bcknd
        ports:
        - containerPort: 80
