apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/front-end:adeff66e9e8540d8c43ee46625632e900fd7cbda
        name: guestbook-ui
        ports:
        - containerPort: 80

