apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-sourcecode-bcknd
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-sourcecode-bcknd
  template:
    metadata:
      labels:
        app: guestbook-ui-sourcecode-bcknd
        tst: tst-1111277
    spec:
      containers:
      - image: omniregistry/back-end:7728e9884ccbc54fc5a0e330a8046dfc2eb3075c
        name: guestbook-ui-bcknd
        ports:
        - containerPort: 80
